run_cmd: "claude -p ${prompt}"

runtime_env_config:
  type: node
  custom_install_cmd: "npm install -g @anthropic-ai/claude-code"

env:
  ANTHROPIC_BASE_URL: "<BASE_URL>" # replace
  ANTHROPIC_API_KEY: "<API_KEY>"   # replace
