run_cmd: "iflow -p ${prompt} --yolo"

runtime_env_config:
  type: node
  custom_install_cmd: "npm i -g @iflow-ai/iflow-cli@latest"

env:
  IFLOW_API_KEY: "<API_KEY>"                  # replace
  IFLOW_BASE_URL: "http://localhost:8080/v1"  # Enter your base url
  IFLOW_MODEL_NAME: "<MODEL_NAME>"            # replace

model_service_config:
  enabled: true
  type: proxy
  start_cmd: "rock model-service start --type ${type} --proxy-base-url <IFLOW_BASE_URL>" # replace <> value
