run_cmd: "iflow -p ${prompt} --yolo"

runtime_env_config:
  type: node
  custom_install_cmd: "npm i -g @iflow-ai/iflow-cli@latest"

env:
  IFLOW_API_KEY: "xxxx" # Not important, just a placeholder
  IFLOW_BASE_URL: "http://localhost:8080/v1"
  IFLOW_MODEL_NAME: "<MODEL_NAME>"   # replace

model_service_config:
  enabled: true
  type: local
