run_cmd: "iflow -p ${prompt} --yolo"

runtime_env_config:
  type: node
  custom_install_cmd: "npm i -g @iflow-ai/iflow-cli@latest"

env:
  IFLOW_API_KEY: "<API_KEY>"         # replace
  IFLOW_BASE_URL: "<BASE_URL>"       # replace
  IFLOW_MODEL_NAME: "<MODEL_NAME>"   # replace